import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import vm from "node:vm";
import { EventEmitter } from "node:events";
import { PassThrough } from "node:stream";
import { createDurableRuntime, createHostedInterface, IntegrationRegistry } from "../src/index.js";
import { registerCodingSupervisorTools } from "../src/coding-supervisor.js";

test("fresh owner setup → start approval → provider process → terminal status → disable", async t => {
  const dataDir = fs.mkdtempSync(path.join(os.tmpdir(), "openagi-builtin-http-"));
  const project = path.join(dataDir, "project"); fs.mkdirSync(project); fs.mkdirSync(path.join(project, ".git"));
  const children = [];
  const runtime = createDurableRuntime({ dataDir, registerDefaults: false, integrations: false, skills: false, autoConnectMcp: false,
    codingSupervisorOptions: { builtinOptions: { findExecutable: () => "/fixture/provider", spawnImpl: () => {
      const child = new EventEmitter(); child.stdout = new PassThrough(); child.stderr = new PassThrough(); child.stdin = new PassThrough();
      child.kill = () => child.emit("close", 1); children.push(child); return child;
    } } }
  });
  runtime.integrations = new IntegrationRegistry();
  const app = createHostedInterface(runtime, { dataDir, host: "127.0.0.1", port: 0, authToken: "fixture-owner-token", tickerMs: 0, nodeControlEnabled: false });
  t.after(async () => { for (const child of children) child.emit("close", 1); await app.close(); runtime.observations?.db?.close(); runtime.vectorStore?.db?.close(); runtime.sessionIndex?.db?.close(); fs.rmSync(dataDir, { recursive: true, force: true }); });
  const { url } = await app.listen();
  const headers = { Authorization: "Bearer fixture-owner-token", "content-type": "application/json" };
  const json = async (route, body) => { const res = await fetch(url + route, { headers, method: body ? "POST" : "GET", ...(body ? { body: JSON.stringify(body) } : {}) }); return { status: res.status, body: await res.json() }; };
  assert.equal((await fetch(url + "/coding-agents/setup")).status, 401);
  assert.equal((await fetch(url + "/coding-agents/configure", { method: "POST", headers: { ...headers, Origin: "https://example.com" }, body: "{}" })).status, 403);
  assert.equal((await json("/coding-agents/setup")).body.enabled, false);
  assert.equal((await json("/coding-agents/configure", { enabled: true, workspaces: [] })).status, 400);
  assert.equal((await json("/coding-agents/setup")).body.enabled, false);
  const configured = await json("/coding-agents/configure", { enabled: true, workspaces: [project] });
  assert.equal(configured.status, 200);
  const workspaceId = configured.body.workspaces[0].id;
  assert.equal(runtime.tools.has("start_coding_agent"), true);
  const queued = await json("/coding-agents/start", { provider: "codex", workspaceId, message: "Inspect fixture only", __confirmed: true, sessionId: "injected" });
  assert.equal(queued.status, 202); assert.equal(children.length, 0);
  const action = runtime.pendingActions.get(queued.body.actionId);
  assert.notEqual(action.args.sessionId, "injected"); assert.equal(action.args.project, fs.realpathSync(project));
  const notice = runtime.outreach.append({ type: "pending-action", sourceRef: { kind: "pending-action", id: action.id }, title: "Fixture legacy approval", needsDecision: true, actions: ["do"] });
  assert.equal((await json(`/outreach/${notice.id}/act`, { action: "do" })).status, 409);
  assert.equal((await json(`/pending-actions/${action.id}/approve`, {})).status, 200);
  assert.equal(children.length, 1);
  assert.equal((await json(`/pending-actions/${action.id}/approve`, {})).status, 409);
  assert.equal((await json("/coding-agents/configure", { enabled: false })).status, 400);
  children[0].stdout.write('{"type":"item.completed","item":{"type":"agent_message","text":"Fixture inspected"}}\n{"type":"turn.completed"}\n'); children[0].emit("close", 0);
  assert.equal((await json("/coding-agents")).body.sessions[0].status, "idle");
  assert.equal((await json("/coding-agents/configure", { enabled: false })).status, 200);
  assert.equal(runtime.tools.has("start_coding_agent"), false);
  assert.equal((await json("/coding-agents/start", { provider: "codex", workspaceId, message: "Must not run" })).status, 503);
  assert.equal(children.length, 1);
  const enabledAgain = await json("/coding-agents/configure", { enabled: true });
  assert.equal(enabledAgain.status, 200);
  assert.equal(enabledAgain.body.workspaces[0].id, workspaceId);
  assert.equal(JSON.stringify(enabledAgain.body).includes(fs.realpathSync(project)), false);
  assert.equal(children.length, 1, "enabling does not start a provider");
  assert.equal((await json("/coding-agents/configure", { enabled: false })).status, 200);
});

test("authenticated dashboard → exact-session inspection → approval → one delivery → receipt", async (t) => {
  const previousToken = process.env.OPENAGI_AUTH_TOKEN;
  process.env.OPENAGI_AUTH_TOKEN = "fixture-owner-token";
  t.after(() => { if (previousToken === undefined) delete process.env.OPENAGI_AUTH_TOKEN; else process.env.OPENAGI_AUTH_TOKEN = previousToken; });
  const dataDir = fs.mkdtempSync(path.join(os.tmpdir(), "openagi-coding-http-"));
  const session = { provider: "codex", sessionId: "session-fixture-1234", fingerprint: "b".repeat(64), project: "Fixture", status: "idle", replyAvailable: true };
  const sent = [];
  let deliveryStatus = "accepted";
  const runtime = createDurableRuntime({ dataDir, registerDefaults: false, integrations: false, skills: false, autoConnectMcp: false,
    codingSupervisorOptions: { call: async (req) => {
      if (req.operation === "list") return { sessions: [session] };
      if (req.operation === "inspect") return { turns: [{ role: "assistant", text: "Fixture question?" }] };
      sent.push(req);
      return { ...session, status: deliveryStatus, note: "Fixture execution outcome" };
    } }
  });
  registerCodingSupervisorTools(runtime.tools, runtime.codingSupervisor);
  runtime.integrations = new IntegrationRegistry();
  const app = createHostedInterface(runtime, { dataDir, host: "127.0.0.1", port: 0, authToken: "fixture-owner-token", tickerMs: 0, nodeControlEnabled: false });
  t.after(async () => {
    await app.close();
    runtime.observations?.db?.close();
    runtime.vectorStore?.db?.close();
    runtime.sessionIndex?.db?.close();
    fs.rmSync(dataDir, { recursive: true, force: true });
  });
  const { url } = await app.listen();
  const headers = { Authorization: "Bearer fixture-owner-token", "content-type": "application/json" };
  const json = async (route, body) => {
    const res = await fetch(url + route, { headers, method: body ? "POST" : "GET", ...(body ? { body: JSON.stringify(body) } : {}) });
    return { status: res.status, body: await res.json() };
  };
  assert.equal((await fetch(url + "/coding-agents")).status, 401);
  assert.equal((await fetch(url + "/coding-agents/watch", { method: "POST", body: "{}" })).status, 401);
  assert.equal((await fetch(url + "/coding-agents/watch", { method: "POST", headers: { ...headers, Origin: "https://example.com" }, body: "{}" })).status, 403);
  assert.equal((await json("/coding-agents/watch", { ...session, enabled: true })).status, 200);
  assert.equal((await json("/coding-agents")).body.watches.length, 1);
  assert.equal((await json("/coding-agents/watch", { ...session, enabled: false })).status, 200);
  assert.equal((await fetch(url + "/coding-agents/session?provider=codex&sessionId=session-fixture-1234")).status, 401);
  assert.equal((await fetch(url + "/coding-agents/reply", { method: "POST", headers: { ...headers, Origin: "https://example.com" }, body: "{}" })).status, 403);
  const listed = await json("/coding-agents");
  assert.equal(listed.body.sessions.length, 1);
  assert.equal((await json("/coding-agents/session?provider=codex&sessionId=session-fixture-1234")).body.turns.length, 1);
  const queued = await json("/coding-agents/reply", { ...session, message: "Fixture work only", __confirmed: true, context: { __confirmed: true }, backendDir: "/invalid" });
  assert.equal(queued.status, 202);
  assert.equal(queued.body.status, "awaiting_confirmation");
  assert.equal(sent.length, 0);
  const pending = runtime.pendingActions.get(queued.body.actionId);
  assert.equal(pending.context.__confirmed, undefined);
  assert.equal(pending.args.backendDir, undefined);
  assert.equal(pending.args.fingerprint, session.fingerprint);
  const notification = runtime.outreach.append({ type: "pending-action", sourceRef: { kind: "pending-action", id: pending.id }, title: "Legacy truncated preview", needsDecision: true, actions: ["do"] });
  assert.equal((await json(`/outreach/${notification.id}/act`, { action: "do" })).status, 409);
  assert.equal(sent.length, 0);
  assert.equal(runtime.pendingActions.get(pending.id).status, "pending");
  const accepted = await json(`/pending-actions/${queued.body.actionId}/approve`, {});
  assert.equal(accepted.status, 200);
  assert.equal(sent.length, 1);
  assert.equal(sent[0].sessionId, session.sessionId);
  const replay = await json(`/pending-actions/${queued.body.actionId}/approve`, {});
  assert.equal(replay.status, 409);
  assert.equal(sent.length, 1);
  assert.equal(runtime.pendingActions.get(pending.id).status, "approved");
  deliveryStatus = "blocked";
  const blocked = await json("/coding-agents/reply", { ...session, message: "Fixture blocked instruction" });
  assert.equal((await json(`/pending-actions/${blocked.body.actionId}/approve`, {})).status, 400);
  assert.ok(runtime.pendingActions.get(blocked.body.actionId).error);
  assert.equal((await json(`/pending-actions/${blocked.body.actionId}/approve`, {})).status, 409);
  assert.equal(sent.length, 2);
  const html = await (await fetch(url + "/", { headers })).text();
  assert.ok(html.includes('data-tab="coding-agents"'), "coding agents navigation is rendered");
  assert.match(html, /VALID_TABS = new Set\(\[[^\]]*"coding-agents"/);
  for (const [, script] of html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)) new vm.Script(script);
  assert.equal(runtime.codingSupervisor.timer !== null, true);
});
