export const lifelogPage = String.raw`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Lifelog · OpenAGI</title><style>
:root{color-scheme:dark}*{box-sizing:border-box}body{font:16px/1.55 system-ui;background:#101713;color:#eff5f0;margin:0}main{max-width:1000px;margin:auto;padding:32px 20px 80px}h1{font-size:36px;margin-bottom:8px}h2{margin-top:0}a{color:#a2ebba}.muted{color:#acc0b1}section,article{background:#18241d;border:1px solid #354a3c;border-radius:16px;padding:22px;margin:20px 0}button,input,select{font:inherit;border:1px solid #52685a;border-radius:8px;background:#22382a;color:inherit;padding:10px 14px}button{cursor:pointer}button:disabled{opacity:.5}button:hover{background:#30503a}.row{display:flex;gap:12px;flex-wrap:wrap;align-items:center}label{display:flex;gap:8px;align-items:center;flex-wrap:wrap}input[type=checkbox]{width:20px;height:20px}.controls{display:grid;gap:16px}p{white-space:pre-wrap;overflow-wrap:anywhere}.quote{border-left:3px solid #87b596;padding:8px 14px;background:#111d15}small{color:#b5c8ba}details{margin:16px 0}summary{cursor:pointer}.beat{display:inline-block;border:1px solid #647e6d;padding:3px 9px;border-radius:20px;margin:3px}#status{min-height:26px}input[type=search]{flex:1;min-width:180px}@media(max-width:600px){main{padding:20px 14px}section,article{padding:16px}.row>button{flex:1}h1{font-size:30px}}
</style></head><body><main><a href="/g2/proactive">← G2 inbox</a><h1>Your conversation lifelog</h1><p class="muted">A record of what you heard, what mattered, and what might happen next. Inferences are suggestions, not instructions or verified identities.</p>
<section class="controls"><div class="row"><select id="nodes" aria-label="Capture device"></select><input id="date" type="date" aria-label="Day"><input id="query" type="search" placeholder="Search words, people or topics" aria-label="Search lifelog"><button id="search">Search</button></div><div class="row"><button id="export">Export matching history</button><button id="erase">Stop memory & delete history</button></div><small>Recording is controlled on G2. Turning off recording stops new capture; retention still applies. Audio is sent to your speech provider, but is not stored in this lifelog.</small></section>
<details><summary>Analysis, privacy & retention</summary><section class="controls"><label><input id="analysis" type="checkbox">Review new moments with AI (sends transcript text to your configured model provider)</label><label>Analysis model <input id="model" placeholder="Exact low-cost model ID" maxlength="100"></label><label>Maximum reviews/day <input id="cap" type="number" min="1" max="48" value="12"></label><label>Keep transcripts <select id="retention"><option value="1">1 day</option><option value="7">7 days</option><option value="30">30 days</option></select></label><label><input id="screen" type="checkbox">Allow viewing nearby screen history on this owner page</label><button id="save">Save settings</button><small>Analysis uses your existing provider budget guard. It has no tools and cannot execute tasks. Speaker labels are your corrections, not voice identity verification. Deleting history removes derived summaries, labels and follow-ups; previously accepted user tasks remain.</small></section></details>
<p id="status" role="status" aria-live="polite"></p><section id="digest"></section><div id="moments"></div><button id="more" hidden>Load more</button></main><script>
const $=id=>document.getElementById(id);let current,offset=0,busy=false;
const params=new URLSearchParams(location.search);let selectedId=params.get('moment')||'';
button('Retry failed analysis (within existing budget)',async()=>{await api({op:'lifelog-retry'});await refresh();},$('status').parentElement);
async function api(body){const r=await fetch('/g2/proactive',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...body,nodeId:$('nodes').value})});const b=await r.json();if(!r.ok)throw Error(b.error||'Request unavailable');return b;}
function node(tag,value,parent,cls){const e=document.createElement(tag);if(value)e.textContent=value;if(cls)e.className=cls;if(parent)parent.append(e);return e;}
function button(label,action,parent){const b=node('button',label,parent);b.onclick=async()=>{b.disabled=true;try{await action();}catch(e){$('status').textContent=e.message;}finally{b.disabled=false;}};return b;}
function time(at){return new Date(at).toLocaleString();}
async function refresh(append=false){if(busy||!$('nodes').value)return;busy=true;try{if(!append)offset=0;const b=await api({op:'lifelog',query:$('query').value,date:$('date').value,id:selectedId||undefined,offset});current=b;$('status').textContent=(b.consentActive?'Memory recording consent active. ':'Memory paused. ')+b.total+' moments · '+b.analysis.status+' · '+b.analysis.attempts+' model calls on '+(b.analysis.day||'no day yet')+(b.analysis.error?' · '+b.analysis.error:'');$('analysis').checked=b.settings.analysis;$('model').value=b.settings.model;$('cap').value=b.settings.maxReviewsPerDay;$('screen').checked=b.settings.screenContext;$('retention').value=b.retentionDays;
if(!append){$('moments').replaceChildren();$('digest').replaceChildren();node('h2','Day at a glance',$('digest'));if(!b.digest.length)node('p','No captured conversations match. Enable conversation memory on G2 to begin.',$('digest'));for(const d of b.digest){const p=node('p',time(d.at)+' · '+d.title+'\n'+d.summary,$('digest'));if(d.inferred)node('small','AI summary · verify against transcript',p);}}
for(const m of b.moments)render(m,b);offset=b.nextOffset;$('more').hidden=offset===null;
}catch(e){$('status').textContent=e.message;}finally{busy=false;}}
function render(m,b){const a=node('article',null,$('moments'));node('small',time(m.at)+' — '+new Date(m.endAt).toLocaleTimeString()+' · '+m.boundary,a);node('h2',m.title,a);if(m.topics.length)node('p',m.topics.join(' · '),a,'muted');if(m.review)node('p',m.review.summary,a);const actions=node('div',null,a,'row');button('Edit title / topics',async()=>{const title=prompt('Moment title',m.title);if(title===null)return;const topics=prompt('Topics, separated by commas',m.topics.join(', '));if(topics===null)return;await api({op:'lifelog-edit',id:m.id,title,topics:topics.split(',').map(x=>x.trim()).filter(Boolean)});await refresh();},actions);button('Merge with previous',async()=>{await api({op:'lifelog-edit',id:m.id,boundary:'merge'});await refresh();},actions);button('Delete moment',async()=>{if(confirm('Delete this conversation and its derived summaries/follow-ups?')){await api({op:'lifelog-delete',id:m.id});await refresh();}},actions);
if(b.settings.screenContext)button('Nearby screen activity',async()=>{const data=await api({op:'lifelog-context',id:m.id});const box=node('section',null,a);node('h3','Nearby in time — not proof of a connection',box);for(const r of data.items)node('p',(r.app||'Screen activity')+' · '+time(r.at)+'\n'+(r.text||''),box);if(!data.items.length)node('p','No nearby indexed screen activity.',box);},actions);
for(const related of m.related||[]){const link=node('a','Related: '+related.title+' · '+[...related.sharedTopics,...related.sharedLabels].join(', '),a);link.href='/g2/lifelog?'+new URLSearchParams({node:$('nodes').value,moment:related.id});node('br',null,a);}
for(const key of m.speakers){const row=node('p',(b.labels[key]||'Speaker '+(Number(key.split(':').at(-1))+1)+' (unidentified)')+' ',a);button('Label speaker',async()=>{const label=prompt('Name/label for this speaker within this capture stream',b.labels[key]||'');if(label!==null){await api({op:'lifelog-label',speakerKey:key,label});await refresh();}},row);}
const beats=node('div',null,a);for(const beat of m.beats)node('span',beat.kind,beats,'beat');
const claims=m.review?.claims||m.beats.filter(x=>x.kind==='commitment'||x.kind==='decision').map(x=>({kind:x.kind,text:x.label,quote:x.label,segmentId:x.segmentId}));
for(const c of claims){const block=node('section',null,a);node('strong','Possible '+c.kind,block);node('p',c.text,block);node('p',c.quote,block,'quote');node('small','Source: '+c.segmentId+' · inferred, not permission',block);if(c.kind==='commitment'||c.kind==='question')button('Confirm follow-up',async()=>{const title=prompt('What do you want to follow up on?',c.text);if(!title)return;const dueAt=prompt('Follow-up date/time with time zone (optional, e.g. 2026-09-08T09:00:00-07:00)','');if(dueAt===null)return;await api({op:'lifelog-followup',segmentId:c.segmentId,title:title.slice(0,180),status:'confirmed',dueAt});await refresh();},block);}
for(const f of b.followups.filter(f=>m.segments.some(s=>s.id===f.segmentId))){const block=node('section',null,a);node('p',f.title+' · '+f.status+(f.dueAt?' · '+time(f.dueAt):''),block);const row=node('div',null,block,'row');for(const status of ['completed','dismissed'])button(status,async()=>{await api({...f,op:'lifelog-followup',status,dueAt:f.dueAt?new Date(f.dueAt).toISOString():null});await refresh();},row);}
const detail=node('details',null,a);node('summary','Original transcript · '+m.segments.length+' segments',detail);for(const s of m.segments){const block=node('div',null,detail);node('small',time(s.at)+' · '+(b.labels[s.speakerKey]||'Unidentified speaker'),block);node('p',s.text,block,'quote');button('Start a new moment here',async()=>{await api({op:'lifelog-edit',id:s.id,boundary:'split'});await refresh();},block);button('Create my task',async()=>{const title=prompt('Task title',s.text.slice(0,180));if(!title||!confirm('Add this to YOUR tasks? It will not be executed automatically.'))return;await api({op:'lifelog-task',segmentId:s.id,title,confirm:true});await refresh();},block);}}
$('search').onclick=()=>{selectedId='';void refresh();};$('nodes').onchange=()=>{selectedId='';void refresh();};$('more').onclick=()=>refresh(true);$('save').onclick=async()=>{try{await api({op:'lifelog-settings',settings:{analysis:$('analysis').checked,model:$('model').value,maxReviewsPerDay:Number($('cap').value),screenContext:$('screen').checked}});await api({op:'configure',settings:{retentionDays:Number($('retention').value)}});await refresh();}catch(e){$('status').textContent=e.message;}};
$('erase').onclick=async()=>{if(confirm('Stop conversation memory and permanently delete all retained conversations and derived history for this device?'))try{await api({op:'delete-memory'});await refresh();}catch(e){$('status').textContent=e.message;}};
$('export').onclick=async()=>{try{const b=await api({op:'lifelog-export',query:$('query').value,date:$('date').value});const url=URL.createObjectURL(new Blob([JSON.stringify(b,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='openagi-lifelog.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){$('status').textContent=e.message;}};
api({op:'devices'}).then(async b=>{for(const n of b.nodes){const o=node('option',n.name||'G2',$('nodes'));o.value=n.nodeId;}if(b.nodes.some(n=>n.nodeId===params.get('node')))$('nodes').value=params.get('node');const s=await api({op:'settings'});$('retention').value=s.settings.retentionDays;await refresh();}).catch(e=>$('status').textContent=e.message);
</script></body></html>`;
